---
- name: "Raspberry Pi Cluster : Setup Firewall"
  hosts: head
  become: true

  vars_files:
      - vars/general/main.yaml
      - vars/general/firewall.yaml

  tasks:
      - name: "Cluster - Firewall : Install required system packages"
        ansible.builtin.apt:
            name: ufw
            state: present

      - name: "Cluster - Firewall : Configure UFW rules"
        tags: "ufw"
        block:
            - name: "Cluster - Firewall : Allow all outgoing traffic by default"
              community.general.ufw:
                  default: allow
                  direction: outgoing
                  comment: "Allow all outgoing traffic"

            - name: "Cluster - Firewall : Deny all incoming traffic by default"
              community.general.ufw:
                  default: deny
                  direction: incoming
                  comment: "Deny all incoming traffic"

            - name: "Cluster - Firewall : Allow app connections"
              community.general.ufw:
                  rule: allow
                  name: "{{ item.name }}"
                  direction: "{{ item.direction }}"
                  comment: "{{ item.comment }}"
                  interface: "{{ item.interface }}"
              loop: "{{ apps }}"
              loop_control:
                  label: "{{ item.name }}"

            - name: "Cluster - Firewall : Allow port connections"
              community.general.ufw:
                  rule: allow
                  port: "{{ item.port }}"
                  direction: "{{ item.direction }}"
                  comment: "{{ item.comment }}"
                  interface: "{{ item.interface }}"
              loop: "{{ ports }}"
              loop_control:
                  label: "{{ item.name }}"

      - name: "Cluster - Firewall : Configure NAT rules"
        tags: "nat"
        block:
            - name: "Cluster - Firewall : Enable packet forwarding"
              ansible.builtin.lineinfile:
                  path: "/etc/sysctl.conf"
                  regexp: "^#net.ipv4.ip_forward=1$"
                  line: "net.ipv4.ip_forward=1"
                  backup: true
              notify: Reload Sysctl

            - name: "Cluster - Firewall : Enable NAT translation"
              ansible.builtin.template:
                  src: "templates/ufw/before.rules.j2"
                  dest: "/etc/ufw/before.rules"
                  mode: "0640"
                  backup: true

            - name: "Cluster - Firewall : Config UFW to forward packets"
              ansible.builtin.lineinfile:
                  path: "/etc/default/ufw"
                  regexp: '^DEFAULT_FORWARD_POLICY="DROP"'
                  line: 'DEFAULT_FORWARD_POLICY="ACCEPT"'
                  backup: true

      - name: "Cluster - Firewall : Enable the firewall"
        community.general.ufw:
            state: enabled

  handlers:
      - name: Reload Sysctl
        ansible.builtin.command: "sysctl -p"
        changed_when: false
