- name: Docker Install
  hosts: nodes
  become: true
  tasks:
    - name: Install required system packages
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true

    - name: Add Docker GPG apt key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: deb [arch=arm64] https://download.docker.com/linux/debian bookworm stable
        state: present

    - name: Update apt and install docker-ce
      ansible.builtin.apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Install Docker Module for Python
      ansible.builtin.apt:
        pkg:
          - python3-docker

    - name: Add docker group
      ansible.builtin.group:
        name: docker

    - name: Add user to docker group
      ansible.builtin.user:
        append: true
        groups:
          - docker
        name: noldona
