username: noldona
release: bookworm

mac_addresses:
  - d8:38:dd:a7:34:33
  - d8:38:dd:a7:34:79
  - d8:38:dd:a7:34:fb
  - d8:38:dd:a7:33:e1
  - d8:38:dd:a7:34:b2
  - d8:38:dd:a7:33:ac
  - d8:38:dd:a7:34:3c
  - d8:38:dd:a7:34:46
  - d8:38:dd:a7:33:0d
  - d8:38:dd:a7:33:e5
  - d8:38:dd:a7:34:49

pip_install_packages:
  - cryptography
  - docker
  - hvac
  - jmespath
  - python-nomad

basic_apt_packages:
  - atop
  - curl
  - jq
  - lynx
  - tree
  - unattended-upgrades
  - vim
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  - python3-pip
  - virtualenv
  - python3-setuptools
  - gnupg

timezone: "America/New_York"

nodes:
  - hostname: server1
    address: 10.0.0.2
    mac_address: d8:38:dd:a7:34:33
  - hostname: server2
    address: 10.0.0.3
    mac_address: d8:38:dd:a7:34:79
  - hostname: server3
    address: 10.0.0.4
    mac_address: d8:38:dd:a7:34:fb
  - hostname: client1
    address: 10.0.0.5
    mac_address: d8:38:dd:a7:33:e1
  - hostname: client2
    address: 10.0.0.6
    mac_address: d8:38:dd:a7:34:b2
  - hostname: client3
    address: 10.0.0.7
    mac_address: d8:38:dd:a7:33:ac
  - hostname: client4
    address: 10.0.0.8
    mac_address: d8:38:dd:a7:34:3c
  - hostname: client5
    address: 10.0.0.9
    mac_address: d8:38:dd:a7:34:46
  - hostname: client6
    address: 10.0.0.10
    mac_address: d8:38:dd:a7:33:0d
  - hostname: client7
    address: 10.0.0.11
    mac_address: d8:38:dd:a7:33:e5
  - hostname: client8
    address: 10.0.0.12
    mac_address: d8:38:dd:a7:34:49
